spring.application.name=alternance-rada

server.port=9000

#PostgreSQL
spring.datasource.url=jdbc:postgresql://192.168.1.35:5432/alternance_radar
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
